djangoESGI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('doctopyt.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('doctopyt.urls')),
]

doctopyt/urls.py
from django.urls import path

from . import views

app_name = 'doctopyt'
urlpatterns = [
    path('creneau/create/', views.createCreneau, name='createCreneau'),
    path('creneau/<int:praticien_id>/', views.visualizeCreneau, name='visualizeCreneau'),
    path('rdv/<int:patient_id>/', views.visualizeRdv, name='visualizeRdv'),
    path('rdv/<int:creneau_id>/reservation/', views.reservationRdv, name='reservationRdv'),
    path('', views.index, name='index'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('me/', views.me, name="me"),
    path('me/specialites/', views.me_specialites, name='me_specialites'),
    path('me/specialites/<int:specialite_pk>/billets/', views.me_billets, name='me_billets'),
    path('me/specialites/<int:specialite_pk>/billets/<int:billet_pk>', views.me_billet, name='me_billet'),
    path('praticiens/', views.praticiens, name="praticiens"),
    path('praticiens/<int:praticien_pk>', views.view_praticien, name="view_praticien"),
    path('praticiens/<int:praticien_pk>/<int:specialite_pk>', views.view_praticien_billets, name="view_praticien_billets"),
    path('praticiens/<int:praticien_pk>/<int:specialite_pk>/<int:billet_pk>', views.view_praticien_billet, name="view_praticien_billet"),
    path('chat/<str:room_name>/', views.chat, name="chat")
]

doctopyt/models.py
from django.db import models
from django.contrib.auth.models import User


class ZoneGeographique(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Specialite(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Praticien_specialite(models.Model):
    specialite = models.ForeignKey(Specialite, on_delete=models.CASCADE, related_name='praticien_specialite')
    praticien = models.ForeignKey('Praticien', on_delete=models.CASCADE, related_name='praticien_specialite')

class Billet(models.Model):
    name = models.CharField(max_length=255)
    presentation = models.TextField()
    praticien_specialite = models.ForeignKey(Praticien_specialite, on_delete=models.CASCADE, related_name='billets')

    def __str__(self):
        return self.name + ' - ' + self.presentation + ' - ' + self.specialite

class Praticien(models.Model):
    user = models.OneToOneField(
            User,
            on_delete=models.CASCADE,
            primary_key=True,
          )
    name = models.CharField(max_length=255)
    presentation = models.TextField()
    zoneGeographique = models.ForeignKey(ZoneGeographique, on_delete=models.CASCADE, default=None, null=True)
    patients = models.ManyToManyField(User, related_name='praticiens')
    specialities = models.ManyToManyField(Specialite, through="Praticien_specialite", related_name='praticiens')


class Creneau(models.Model):
    datetime_debut = models.DateTimeField()
    datetime_fin = models.DateTimeField()
    praticien = models.ForeignKey(Praticien, on_delete=models.CASCADE)


class RendezVous(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    creneau = models.ForeignKey(Creneau, on_delete=models.CASCADE, related_name='rdv')
    praticien = models.ForeignKey(Praticien, on_delete=models.CASCADE)

doctopyt/forms.py
from django import forms
from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple, CharField, ChoiceField, PasswordInput
from django.contrib.auth.models import User
from .models import Praticien, Specialite, ZoneGeographique, Billet
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm


class BilletForm(ModelForm):
    class Meta:
        model = Billet
        fields = ['name','presentation']

class CreateCreneauForm(forms.Form):
    datetime_debut = forms.DateTimeField(widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control mb-3'},
            format='%Y-%m-%dT%H:%M'), label='Date de debut')
    datetime_fin = forms.DateTimeField(widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control mb-3',},
            format='%Y-%m-%dT%H:%M'), label='Date de fin')

class PraticienForm(ModelForm):
    class Meta:
        model = Praticien
        fields = ['name', 'presentation', 'zoneGeographique', 'specialities']

    specialities = ModelMultipleChoiceField(
        queryset=Specialite.objects.all(),
        widget=CheckboxSelectMultiple,
        required=False,
    )

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    presentation = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(PraticienForm, self).__init__(*args, **kwargs)

        # Load choices here so db calls are not made during migrations.
        self.fields['zoneGeographique'].required = False

class SearchPraticienForm(ModelForm):
    class Meta:
        model = Praticien
        fields = ['name', 'zoneGeographique', 'specialities']

    name = CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    zoneGeographique = ChoiceField(
        choices=(('', '')),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    specialities = ModelMultipleChoiceField(
        queryset=Specialite.objects.all(),
        widget=CheckboxSelectMultiple,
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(SearchPraticienForm, self).__init__(*args, **kwargs)

        # Load choices here so db calls are not made during migrations.
        self.fields['zoneGeographique'].choices = map(
            lambda z: (z.id, z.name), ZoneGeographique.objects.all())


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'type', 'password1', 'password2']

    type = ChoiceField(
        choices=(('patient', 'Patient'), ('praticien', 'Praticien')),
        required=False
    )

doctopyt/views.py
from django.http import HttpResponseRedirect
from doctopyt.models import Creneau, RendezVous
from doctopyt.forms import CreateCreneauForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404
from .models import Specialite, Praticien, ZoneGeographique, Billet, Praticien_specialite
from .forms import PraticienForm, SearchPraticienForm, RegisterForm, BilletForm

def is_practicien(func):
    def check_user_is_practicien(request, *args, **kwargs):
        if request.user.is_authenticated and hasattr(request.user, 'praticien'):
            return func(request, *args, **kwargs)
        return redirect('doctopyt:index')
    return check_user_is_practicien

def index(request):
    return render(request, 'doctopyt/index.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ('Connexion réussie'))
            return HttpResponseRedirect(request.GET.getlist('next')[0]) if request.GET.getlist('next') else redirect('doctopyt:index')
        else:
            messages.success(request, ('Erreur de connexion, veuillez réessayer'))
            return redirect('doctopyt:login')
    else:
        return render(request, 'authentication/login.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, ('Vous êtes déconnecté'))
    return redirect('doctopyt:index')

def register(request):
    form = RegisterForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)

            type = form.cleaned_data.get('type')
            if type == 'praticien':
                praticien = Praticien(user_id=user.id,name=username)
                praticien.save()

            login(request, user)
            messages.success(request, ('Vous êtes inscrit et connectés'))
            return redirect('doctopyt:me') if type == 'praticien' else redirect('doctopyt:index')
        else:
            form = RegisterForm()
            messages.success(request, ('Erreur dans l\'inscription, veuillez réessayer'))
            return redirect('doctopyt:register')
    else:
        return render(request, 'authentication/register.html', {'form':form,})

# Create your views here.
@login_required(login_url='/login_user/')
def me_specialites(request):
    user = request.user
    try:
      praticien = user.praticien
    except:
      return redirect('doctopyt:index')
    return render(request, 'doctopyt/me_specialites.html', {"praticien_specialites": praticien.praticien_specialite.all()})

@require_http_methods(["GET","POST"])
@login_required(login_url='/login_user/')
def me_billets(request, specialite_pk):
  user = request.user
  try:
    praticien = user.praticien
  except:
    return redirect('doctopyt:index')
  try:
    praticien_specialite = praticien.praticien_specialite.get(specialite_id=specialite_pk)
  except:
    raise(Http404)
  if request.method == 'GET':
      form = BilletForm()
      return render(request, 'doctopyt/billets.html', {
        "specialite": praticien_specialite.specialite,
        "billets": praticien_specialite.billets.all(),
        "praticien": praticien,
        "form": form,
        "me": True
      })
  else:
      form = BilletForm(request.POST)
      if form.is_valid():
          billet = form.save(commit=False)
          billet.praticien_specialite = praticien_specialite
          billet.save()
      return redirect('doctopyt:me_billets', specialite_pk=specialite_pk)

@require_http_methods(["GET","POST","DELETE"])
@login_required(login_url='/login_user/')
def me_billet(request,specialite_pk,billet_pk):
    user = request.user
    try:
        praticien = user.praticien
    except:
        return redirect('doctopyt:index')
    try:
        praticien_specialite = praticien.praticien_specialite.get(specialite_id=specialite_pk)
    except:
        raise(Http404)
    try:
        billet = praticien_specialite.billets.get(id=billet_pk)
    except:
        raise(Http404)

    if request.method == "GET":
        form = BilletForm(instance=billet)
        return render(request, 'doctopyt/billet.html', {"billet": billet, "form": form, "me": True})
    elif request.method == "POST":
        if request.POST.getlist("_method")[0] == "put":
            form = BilletForm(request.POST)
            if form.is_valid():
                billet.name = form.cleaned_data.get('name')
                billet.presentation = form.cleaned_data.get('presentation')
                billet.save()
            return redirect('doctopyt:me_billet', specialite_pk=specialite_pk, billet_pk=billet_pk)
        elif request.POST.getlist("_method")[0] == "delete":
            billet.delete()
            return redirect('doctopyt:me_billets', specialite_pk=specialite_pk)

@login_required(login_url='/login_user/')
@is_practicien
# Create your views here.
def createCreneau(request):
    if request.method == 'POST':
        form = CreateCreneauForm(request.POST)
        if form.is_valid():
            c = Creneau() # Definition d'un objet modele
            c.datetime_debut = form.cleaned_data['datetime_debut']
            c.datetime_fin = form.cleaned_data['datetime_fin']
            c.praticien = request.user.praticien
            c.save()
            return HttpResponseRedirect('/creneau/' + str(request.user.praticien.pk)) # Redirection vers une url
    else:
        # generation de la form initialement vide
        form = CreateCreneauForm()
    return render(request, 'doctopyt/createCreaneau.html',  {'form': form})


def visualizeCreneau(request, praticien_id):
    return render(request, 'doctopyt/visualizeCreneau.html', {'praticien_id': praticien_id, 'creneaux': Creneau.objects.filter(praticien=praticien_id).filter(datetime_debut__gte=timezone.now()).filter(rdv__isnull=True).order_by('datetime_debut')})

@login_required(login_url='/login_user/')
def reservationRdv(request, creneau_id):
    creneau = Creneau.objects.get(pk=creneau_id)
    rdv = RendezVous()
    rdv.user = request.user
    rdv.creneau = creneau
    rdv.praticien = creneau.praticien
    rdv.save()
    return HttpResponseRedirect('/rdv/' + str(request.user.id))

def visualizeRdv(request, patient_id):
    return render(request, 'doctopyt/visualizeRdv.html', {'rdvs': RendezVous.objects.filter(user=patient_id).filter(creneau__datetime_fin__gte=timezone.now()).order_by('creneau__datetime_debut')})

@login_required(login_url='/login_user/')
@require_http_methods(["GET","POST"])
def me(request):
    user = request.user

    praticien = user.praticien if hasattr(user, 'praticien') else None

    if request.method == "GET" or praticien == None:
        form = PraticienForm(instance=praticien) if praticien is not None  else None

        return render(request, 'doctopyt/me.html', {"user": user, "praticien": praticien, 'form': form})
    else:
        f = PraticienForm(request.POST)
        if f.is_valid():
            praticien = f.save(commit=False)
            praticien.user = user
            specialitiesIds = request.POST.getlist('specialities')
            praticien.specialities.set([Specialite.objects.get(pk=id) for id in specialitiesIds])
            praticien.save()
        return redirect("doctopyt:me")

@require_http_methods(["GET"])
def praticiens(request):
    search = {}
    if (request.GET.getlist('name')):
        search['name__contains'] = request.GET.getlist('name')[0]
    if (request.GET.getlist('zoneGeographique')):
        search['zoneGeographique_id'] = int(request.GET.getlist('zoneGeographique')[0])

    praticiens = []
    if (request.GET.getlist('specialities')):
        praticiens = {}
        for speciality in Specialite.objects.filter(id__in=map(int,request.GET.getlist('specialities'))):
            for praticien in speciality.praticiens.filter(**search):
                praticiens[praticien.user_id] = praticien
        praticiens = praticiens.values()
    else:
        praticiens = Praticien.objects.filter(**search)

    form = SearchPraticienForm(request.GET)
    return render(request, 'doctopyt/praticiens.html', {"praticiens": praticiens, 'form': form})

def view_praticien(request, praticien_pk):
    try:
        praticien = Praticien.objects.get(pk=praticien_pk)
    except:
        raise Http404

    return render(request, 'doctopyt/view_praticien.html', {"praticien": praticien})

def view_praticien_billets(request, praticien_pk, specialite_pk):
    try:
        praticien = Praticien.objects.get(pk=praticien_pk)
    except:
        raise Http404
    try:
        praticien_specialite = praticien.praticien_specialite.get(specialite_id=specialite_pk)
    except:
        raise Http404
    return render(request, 'doctopyt/billets.html', {
        "praticien": praticien,
        "billets": praticien_specialite.billets.all(),
        "specialite": praticien_specialite.specialite,
        "me": False
    })

def view_praticien_billet(request, praticien_pk, specialite_pk, billet_pk):
    try:
        praticien = Praticien.objects.get(pk=praticien_pk)
    except:
        raise Http404
    try:
        praticien_specialite = praticien.praticien_specialite.get(specialite_id=specialite_pk)
    except:
        raise Http404
    try:
        billet = praticien_specialite.billets.get(id=billet_pk)
    except:
        raise Http404

doctopyt/templates/doctopyt/billet.html
{% extends 'base.html' %}

{% block content %}
{% if me %}
    <a href="{% url 'doctopyt:me_billets' specialite_pk=billet.praticien_specialite.specialite_id %}" >Retour</a>
    <h1 class="text-center my-5">Visionner/Editer le billet '{{billet.name}}'</h1>
{% else %}
    <a href="{% url 'doctopyt:view_praticien_billets' praticien_pk=praticien.user_id specialite_pk=praticien_specialite.specialite_id %}" >Retour</a>
    <h1 class="text-center my-5">Billet du praticien '{{praticien.name}}' spécialité '{{praticien_specialite.specialite.name}}'</h1>
{% endif %}

<div id="show">
    <div>
        <label>Nom :</label>
        <b>{{billet.name}}</b>
    </div>
    <div>
        <label>Présentation :</label>
        <p>{{billet.presentation}}</p>
    </div>
</div>
{% if me %}
<form id="form" style="display: none" method="post">
    <input type="hidden" name="_method" value="put" />
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Valider" />
</form>

<input id="show_or_edit_button" type="button" value="Modifier"/>
<br/><br/>
<form action="{% url 'doctopyt:me_billet' specialite_pk=billet.praticien_specialite.specialite_id billet_pk=billet.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="_method" value="delete" />
    <input type="submit" value="Supprimer">
</form>


<script>
    let editing = false;
    document.getElementById("show_or_edit_button").addEventListener("click", function() {
        editing = !editing;
        this.value = editing ? "Visionner" : "Modifier"
        document.getElementById("show").style.display = editing ? "none" : "block";
        document.getElementById("form").style.display = editing ? "block" : "none";
    })
</script>
{% endif %}
{% endblock content %}

doctopyt/templates/doctopyt/billets.html
{% extends 'base.html' %}

{% block content %}
{% if me %}
  <a href="{% url 'doctopyt:me_specialites' %}" >Retour</a>
  <h1>
    Gestion des billets pour la specialitée '{{specialite.name}}'
  </h1>
  <button onclick="showForm()">Ajouter +</button>
  <br><br>
  <div id="form-ticket" style="display: none;">
    <form method="post" style="display: flex; flex-direction: column; width: 25%;">
      <h2>Fomulaire du billet:</h2>
      {% csrf_token %}
      {{ form }}
      <input class="btn btn-success" type="submit" value="Enregistrer" style="background-color: #2E86C1; color: white; margin-top: .5rem">
    </form>
  </div>
{% else %}
  <a href="{% url 'doctopyt:view_praticien' praticien_pk=praticien.user_id %}" >Retour</a>
{% endif %}

{% if me %}
  <h3>Liste de vos billets</h3>
{% else %}
  <h1>Liste des billets du praticien '{{praticien.name}}' spécialité '{{specialite.name}}'</h1>
{% endif %}

{% if billets|length > 0 %}
  <ul>
    {% for billet in billets %}
      <li>
        {% if me %}
          <span>{{billet.name}}</span>
          <a class="btn btn-primary my-2" href="{% url 'doctopyt:me_billet' specialite_pk=specialite.id billet_pk=billet.id %}">Voir/Modifier</a>
          <form action="{% url 'doctopyt:me_billet' specialite_pk=specialite.id billet_pk=billet.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="_method" value="delete" />
            <input class="btn btn-danger" type="submit" value="Supprimer">
          </form>
        {% else %}
          <a class="btn btn-prumary" href="{% url 'doctopyt:view_praticien_billet' praticien_pk=praticien.user_id specialite_pk=specialite.id billet_pk=billet.id  %}" >{{billet.name}}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <span>Aucun billet</span>
{% endif %}

{% if me %}
<script>
  function showForm() {
    var formTicket = document.getElementById("form-ticket");
    if (formTicket.style.display === "none") {
      formTicket.style.display = "block";
    } else {
      formTicket.style.display = "none";
    }
  }
</script>
{% endif %}

{% endblock %}

doctopyt/templates/doctopyt/chat.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Chat</h1>
    <textarea id="chat-log" cols="100" rows="20"></textarea>
    <br>
    <input id="chat-message-input" type="text" size="100">
    <br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        // onmessage - An event listener to be called when a message is received from the server.
        chatSocket.onmessage = function(e) {
            // JSON.parse() converts the JSON object back into the original object,
            // then examine and act upon its contents.
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        // onclose - An event listener to be called when the connection is closed.
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;

            // Send the msg object as a JSON-formatted string.
            chatSocket.send(JSON.stringify({
                'message': message
            }));

            // Blank the text input element, ready to receive the next line of text from the user.
            messageInputDom.value = '';
        };
    </script>
{% endblock %}

doctopyt/templates/doctopyt/createCreaneau.html
{% extends '../base.html' %}
{% block content %}
<h1 class="text-center my-5">Créer un créneau</h1>
    <form action="/creneau/create/" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="submit text-center">
            <input class="btn btn-success" type="submit" name="Créer">
        </div>
    </form>
{% endblock %}

doctopyt/templates/doctopyt/index.html
{% extends '../base.html' %}

{% block content %}
<h1 class="text-success text-center my-5">Bienvenue sur Doctopyt</h1>
<img src="https://www.3ssante.com/wp-content/uploads/2020/07/caduc%C3%A9e-pharmaciens-1.jpg" alt="doctopyt" class="img-fluid mx-auto d-block" style="width: 50%;">
{% endblock %}

doctopyt/templates/doctopyt/me.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Votre compte</h1>
    <span>Vous êtes un
        {% if praticien %}
            praticien
        {% else %}
            patient
        {% endif %}
    </span>
    <div>
        <span>Votre username :</span>
        <span>
            {% if user.username %}
                {{ user.username }}
            {% else %}
                Non défini
            {% endif %}
        </span>
    </div>
    {% if praticien %}
        <a class="btn btn-primary" target="_blank" href="{% url 'doctopyt:me_specialites' %}">Voir vos billets par spécialités</a>
        <a class="btn btn-primary" target="_blank" href="{% url 'doctopyt:createCreneau' %}">Créer des créneaux</a>
    {% endif %}
    {% if form %}
        <h2 class="text-center">Editer vos données</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Votre nom de praticien</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.presentation.id_for_label }}">Votre présentation</label>
                {{ form.presentation }}
            </div>
            <div class="form-group">
                <label for="{{ form.zoneGeographique.id_for_label }}">Zone géographique</label>
                {{ form.zoneGeographique }}
            </div>
            <div class="form-group">
                <label for="{{ form.specialities.id_for_label }}">Spécialités</label>
                {{ form.specialities }}
            </div>
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Valider">
            </div>
        </form>
    {% endif %}
{% endblock content %}

doctopyt/templates/doctopyt/praticiens.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Recherche de praticiens</h1>
    <div>
        <h2>Filtres</h2>
        <form>
            <div class="form-group">
                <label>Par nom de patricien :</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label>Par zone géographique</label>
                {{ form.zoneGeographique }}
            </div>
            <div class="form-group">
                <label>Par spécialités</label>
                {{ form.specialities }}
            </div>
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Filtrer"/>
            </div>
        </form>
    </div>
    <ul>
        {% for praticien in praticiens %}
            <li>
                <a href="{% url 'doctopyt:view_praticien' praticien_pk=praticien.user_id %}">{{ praticien.name }}</a>
                <div>
                    Spécialités :
                    {% for speciality in praticien.specialities.all %}
                        <div style="display: inline-block">{{ speciality.name }}</div>
                    {% endfor %}
                    {% if praticien.specialities.all|length == 0 %}Aucune{% endif %}
                </div>
                <div>
                    Zone :
                    {% if praticien.zoneGeographique %}
                        {{ praticien.zoneGeographique.name }}
                    {% else %}
                        Aucune
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

doctopyt/templates/doctopyt/view_praticien.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">{{ praticien.name }}</h1>
    <div>
        Présentation :
        {% if praticien.presentation %}
            <p>
                {{ praticien.presentation }}
            </p>
        {% else %}
            Aucune
        {% endif %}
    </div>
    <div>
        <a class="btn btn-primary" href="{% url 'doctopyt:visualizeCreneau' praticien.pk %}">Prendre rendez-vous</a>
    </div>
    <div>
        Spécialités :
        {% if praticien.praticien_specialite.all|length > 0 %}
            <ul>
                {% for praticien_specialite in praticien.praticien_specialite.all %}
                    <li>
                        {{ praticien_specialite.specialite.name }}
                        <a href="{% url 'doctopyt:view_praticien_billets' praticien_pk=praticien.user_id specialite_pk=praticien_specialite.specialite_id %}">
                            Voir les billets ({{ praticien_specialite.billets.all|length }})
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            Aucune
        {% endif %}
    </div>
    <div>
        Zone géograpique :
        {% if praticien.zoneGeographique %}
            <a target="_blank"
               href="{% url 'doctopyt:praticiens' %}?zoneGeographique={{ praticien.zoneGeographique.id }}">
                {{ praticien.zoneGeographique.name }}
            </a>
        {% else %}
            Aucune
        {% endif %}
    </div>
    <div>
        Billets :
        {% if praticien.billets.all|length > 0 %}
            <ul>
                {% for billet in praticien.billets.all %}
                    <li>
                        <h2>{{ billet.name }}</h2>
                        <p>
                            {{ billet.presentation }}
                        </p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            Aucun
        {% endif %}
    </div>
</br>
<div>
    Envoyer un message au praticien :
</br>
<div class="mb-3">
    <label for="room-name-input" class="form-label">Identifiant du praticien :</label>
    <input type="hidden"
           id="room-name-input"
           class="form-control"
           value="{{ praticien.user_id }}"
           disabled>
    {{ praticien.user_id }}
</input>
</br>
<input id="room-name-submit" type="button" value="Entrer">
</div>
</div>
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>
{% endblock %}